#!/usr/bin/env bash

NEW_RELIC_LICENSE_KEY=$1
SERVICE_BUS=$2

echo "NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY"
echo "SERVICE_BUS=$SERVICE_BUS"

npm install

NEW_RELIC_LICENSE_KEY="$NEW_RELIC_LICENSE_KEY" SERVICE_BUS="$SERVICE_BUS" npm run start
