FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

# Publish your application.
COPY bin/Debug/netcoreapp3.1/publish /app

# Install the agent
RUN apt-get update && apt-get install -y wget ca-certificates gnupg \
&& echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee /etc/apt/sources.list.d/newrelic.list \
&& wget https://download.newrelic.com/548C16BF.gpg \
&& apt-key add 548C16BF.gpg \
&& apt-get update \
&& apt-get install -y newrelic-netcore20-agent

# Enable the agent
ENV CORECLR_ENABLE_PROFILING=1 \
CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A} \
CORECLR_NEWRELIC_HOME=/usr/local/newrelic-netcore20-agent \
CORECLR_PROFILER_PATH=/usr/local/newrelic-netcore20-agent/libNewRelicProfiler.so \
NEW_RELIC_LICENSE_KEY=CHANGE_ME \
NEW_RELIC_APP_NAME=backend \
NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true \
SERVICE_BUS=CHANGE_ME

WORKDIR /app

ENTRYPOINT ["dotnet", "./backend.dll"]
